### PR TITLE
draft for hosting zoomify images through github

### PR DESCRIPTION
**Pull request by thehandsomepanther**
i tried to be as beginner-friendly as possible, but there are definitely a lot of places where first-time users could get tripped up. i think a little user testing for language and clarity would be helpful here.

### CODE REVIEW

**Comment by scott2b** [comment]
Is it possible to do this with github's file upload instead of committing via git? seems like that would be easier for beginners

**Comment by thehandsomepanther** [comment]
@scott2b github's web client doesn't support file upload, so it is possible but the user would have to recreate every `TileGroupX` directory and then manually drag all the files in. i do agree though that committing through github desktop or even command line git could be a hurdle for some users

**Comment by scott2b** [comment]
ok. fair point. This seems fine to merge

**Comment by rosaliechan** [comment]
I think one thing is, you could also include how to push these files via command line. While it's good to include the Desktop app for beginners, I think it would also be good to have the command line option in there.
The second is, I think the instructions for how to link to the tiles was a bit confusing.  Perhaps you could include a screenshot of the link you use for the StoryMap because it can be unclear what link users should be looking to use.

**Comment by thehandsomepanther** [comment]
@rosaliechan i kind of assumed that if someone knew how to use git via the command line then they would understand that all this process is doing is creating/pushing to a new repo and then just turning it into a github page (that's why i briefly mentioned the command line in step 4). do you think we need a separate command line tutorial? id be concerned with providing too many options to non-technical users, especially ones who are coming from something like google drive or dropbox hosting which is as simple as uploading a bunch of files and then getting a special url
i can address the link issue though

**Comment by thehandsomepanther** [comment]
i know that i have way too many `<br>` tags as of the last commit, but i can't find a better way to add spacing in between paragraphs/images without messing up the list numbers
also, does anyone have github desktop on a windows machine that we can test this with?

**Comment by scott2b** [comment]
lgtm

**Pull request merged**
