### PR TITLE
Added AWS documentation

### PR DESCRIPTION
**Pull request by mazhang2718**
Here's the basic outline of Gigapixel AWS documentation! I have a couple of more pictures to add, but I haven't quite figured out markdown yet.

### CODE REVIEW

**Comment by scott2b** [comment]
looking good. For the zoomify link - link directly to the zoomify content: https://storymap.knightlab.com/gigapixel/#zoomify-export

Overall organization and linking (e.g. linking to github tutorial) will get sorted later. Once we have these written up, they will actually need to be incorporated into the website. Pushing them here as markdown is fine for now

**Comment by rosaliechan** [comment]
Looks good. Pretty straightforward

**Comment by thehandsomepanther** [comment]
@mazhang2718 I would use the exact language amazon has on their website to identify pieces of important information (specifically for step 2, and maybe for step 6), since they do offer a lot of options and it can be difficult for people without a technical background to parse meaning out of all the jargon on the website. 
I'd also include what the user should expect to happen after clicking on a link (e.g. will they be redirected, and if so, to where), like you have them do in step 2.
also, does compression (step 4) work in the same way for both macs and PCs? I think on PC you have to right-click and then go to send > to compressed file (zip) or something that's a bit more roundabout.

**Comment by rosaliechan** [comment]
Also maybe add id you want the entire filled, you need to set the map as cartography, since we found that image stops getting bigger at a certain point.

**Comment by rosaliechan** [comment]
This might not specifically be for Amazon/Github, but we also need to make it clear in the instructions to zoomify the image size to at least 10,000px.

**Pull request merged**
