### PR TITLE
Create event for Gigapixel to send to Google Analytics

### PR DESCRIPTION
**Pull request by rosaliechan**
In edit.html, I add an event to send to the Google Analytics if the map_type is zoomify.  If it's zoomify, it will send an event to Google Analytics called zoomify.
@scott2b @mazhang2718

### CODE REVIEW

**Comment by rosaliechan** [comment]
I tested it using fab build, and I use an HTML embed tester to test it out.  Here's what shows up in Google Analytics
screen shot 2016-11-07 at 12 48 22 pm

**Comment by scott2b** [comment]
reviewing this, I am confused as to why in the current code the pageview event is only sent for zoomify map types. Can one of you explain this @zachwise or @JoeGermuska ?

**Comment by scott2b** [comment]
I think i misread the code in an earlier comment. will review this further tomorrow

**Comment by scott2b** [comment]
This appears to me to be sending events for the StoryMap editor tool. What we want is to send zoomify events for StoryMaps that are embedded in the wild. I believe the code where similar events are sent is here: https://github.com/NUKnightLab/StoryMapJS/blob/master/source/embed/index.html#L45

**Comment by scott2b** [comment]
replaced by #333

**Pull request closed without merging**
