### PR TITLE
Create bg.js

### PR DESCRIPTION
**Pull request by zkvvoob**
Bulgarian language

### CODE REVIEW

**Comment by JoeGermuska** [comment]
Thank you.

**Comment by zkvvoob** [comment]
Be my guest.

Is there a way to use this language straight away on a self-hosted StoryMapJS? I added it to the local subfolder and added `"language":"bg"` in the json, but nothing's changed yet. Perhaps I've done something wrong?

**Comment by JoeGermuska** [comment]
We've updated storymap.knightlab.com so you may not need to do this.

But also, I just did a simple test that verifies that StoryMap picks up language files from a local "distribution" if it is set up correctly, so you may have done something wrong. If you want to pursue this, please post a link to a page on a server that demonstrates the error.

**Comment by zkvvoob** [comment]
Before that, could you please confirm for me whether I should use the JS and CSS in the `compiled` folder?

**Comment by JoeGermuska** [comment]
The compiled folder is not automatically managed. It's meant more as a development time tool than as a distribution.

That said, we are beginning to experiment with publishing a distribution to our CDN. So the best way to host your own files would be to download https://cdn.knightlab.com/libs/storymapjs/latest/storymapjs.zip

**Comment by zkvvoob** [comment]
That's absolutely fabulous. Now it works! Thank you!

**Comment by JoeGermuska** [comment]
great!

**Pull request merged**
